//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YayınMvcDbF.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class kanalSet
    {
        public int KanaIno { get; set; }
        public string kanaladi { get; set; }
        public int ciro { get; set; }
        public string adres { get; set; }
        public int reyting { get; set; }
        public int yayınId { get; set; }
    
        public virtual yayinSet yayinSet { get; set; }
    }
}
