//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YayınMvcDbF.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class yayinSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public yayinSet()
        {
            this.kanalSet = new HashSet<kanalSet>();
            this.sorumluSet = new HashSet<sorumluSet>();
        }
    
        public int Id { get; set; }
        public string yayinadi { get; set; }
        public System.DateTime yayıntarih { get; set; }
        public int reyting { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kanalSet> kanalSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sorumluSet> sorumluSet { get; set; }
    }
}
